### PR TITLE
Adding check for request.POST (django >=1.9) cf. request.REQUEST (django <= 1.8)

### PR DESCRIPTION
**Pull request by jamonation**
Here's a little conditional that will handle older django versions and recent 1.9 and newer when calling preview on a markdown field.

### CODE REVIEW

**Comment by jamonation** [comment]
Hey @klen or @yavorskiy - do you need anything else to get this merged into master? I made sure travis will build, and this is working for those of using Django 1.9.x.

For reference, it looks like coverage 4.x doesn't need the `[report]` section for django_mardown given the size of the project, [since it will report on anything in [run] by default](http://coverage.readthedocs.org/en/coverage-4.0.3/source.html#execution). So I removed that section and everything looks good.

Would either of you mind reviewing this PR?

Cheers!

**Comment by iLikeKoffee** [comment]
@jamonation Awesome fix! Hope that will be merged! Thank you!

**Comment by jgruhl** [comment]
@klen are you still able to support this? I'd be willing to support at least the PR's that address the django 1.9 updates.

**Comment by ajoyoommen** [comment]
This PR needs to be merged.

**Review by ajoyoommen — APPROVED** [review]

**Pull request closed without merging**
