### PR TITLE
Fixing static_url issue, making package use MarkdownFields instead of Textfields.

### PR DESCRIPTION
**Pull request by wldcordeiro**
Fixing issue in #39 and some other changes.

Fixing issue with static_url setting overriding the user's since it relied on an or that would eval

to the user's media_url. Also modified the ModelAdmins to only override the MarkdownFields instead of
Textfields so that Textfields display normally unless users specify it as MarkdownField's.

### CODE REVIEW

**Comment by klen** [comment]
Thank you.

**Comment by nielsonsantana** [comment]
I'm having problems with this new settings. 
After I run:

```
 ./manage.py collectstatic
```

My statics are stored in a folder named `assets`. All my settings are:

```
MEDIA_ROOT = normpath(join(SITE_ROOT, 'media'))
MEDIA_URL = '/media/'
STATIC_ROOT = normpath(join(SITE_ROOT, 'assets'))
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    normpath(join(SITE_ROOT, 'static')),
)
```

But, what would be the value for `MEDIA_URL`, since the value should be diferent of `STATIC_URL`. Im my tests, `MEDIA_URL` work with value `/static/`, but django don't allow this var  be same. Media folder, being accessible to download, have any security issue?
How are you doing it?

**Comment by wldcordeiro** [comment]
@nielsonsantana Normally `/media/` would be `MEDIA_URL` I had an issue with this plugin because it was serving things that should be in `/static/` from the `/media/` URL. Here's the relevent snippet I have in my configurations.

``` py
 # STATIC FILE CONFIGURATION
    # See: https://docs.djangoproject.com/en/dev/ref/settings/#static-root
    STATIC_ROOT = join(os.path.dirname(BASE_DIR), 'staticfiles')

    # See: https://docs.djangoproject.com/en/dev/ref/settings/#static-url
    STATIC_URL = '/static/'

    # See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
    STATICFILES_DIRS = (
        join(BASE_DIR, 'static'),
    )

    # See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
    STATICFILES_FINDERS = (
        'django.contrib.staticfiles.finders.FileSystemFinder',
        'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    )
    # END STATIC FILE CONFIGURATION

    # MEDIA CONFIGURATION
    # See: https://docs.djangoproject.com/en/dev/ref/settings/#media-root
    MEDIA_ROOT = join(BASE_DIR, 'media')

    # See: https://docs.djangoproject.com/en/dev/ref/settings/#media-url
    MEDIA_URL = '/media/'
    # END MEDIA CONFIGURATION
```

**Comment by wldcordeiro** [comment]
@klen This issue is actually fixed in the newest PR #41 I had missed some things and this gets it working properly.

**Comment by nielsonsantana** [comment]
Thanks @wldcordeiro. 
I merged locally with your PR #41, and worked well.
However, I had a problem with the view `preview`. The css aren't loading.
Then, I solved this problem changing `preview.html`, calling `static`.

```
 {% load django_markdown %}
+{% load staticfiles %}

 <!DOCTYPE html>
 <html>
@@ -6,7 +7,7 @@
 <base target="_blank">
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
 <title>markItUp! preview</title>
-<link rel="stylesheet" type="text/css" href="{{ css }}" />
+<link rel="stylesheet" type="text/css" href="{% static css %}" />
 </head>
```

Also, I changed `views.py`.

```
 from django.core.files.storage import default_storage
 from django.shortcuts import render

@@ -20,5 +22,5 @@ def preview(request):
     return render(
         request, settings.MARKDOWN_PREVIEW_TEMPLATE, dict(
             content=request.REQUEST.get('data', 'No content posted'),
-            css=default_storage.url(settings.MARKDOWN_STYLE)
+            css=settings.MARKDOWN_STYLE
         ))
```

Did you had problem with `preview`?

**Comment by wldcordeiro** [comment]
I didn't have an issue with the preview within the admin page @nielsonsantana  but I modified my fork and have made changes similar to what you pointed out.

**Comment by nielsonsantana** [comment]
Great @wldcordeiro!! 
Thanks!

**Pull request merged**
