### PR TITLE
added django 1.10  compatibility 

### PR DESCRIPTION
**Pull request by sv0**
Changes:
- removed **request.REQUEST** (replaced with **request.POST**)
- use list of urls instead of 'patterns' in urls.py ( for Django >= 1.8).
- 'django.conf.urls.patterns()' will be removed in Django 1.10

### CODE REVIEW

**Comment by filipeximenes** [comment]
@sv0 this project seems not be maintained anymore and the owner does not seem interested in even merging PRs or even answering messages. Your PR is very important, you should consider renaming the project and deploying it under this new name to PyPI so we can continue using it (just make sure you keep compatible licences and credits). 

Consider the names:
django-markdown-fields
django-markdown-forms
django-markdown-utils

Hope to hear from you!

**Comment by CostantinoGrana** [comment]
@sv0 I agree with @filipeximenes. Please make your branch an official new project. It works perfectly.

**Comment by sv0** [comment]
@filipeximenes @CostantinoGrana
OK.
I will do it just after returning from the vacation.

**Comment by sv0** [comment]
I've created a new repository  https://github.com/sv0/django-markdown-app for **django-markdown** application.

The package is also available on  PyPI:
https://pypi.python.org/pypi/django-markdown-app

@filipeximenes  unfortunately the name **django-markdown-utils** is already taken.
So I've chosen another one. I hope it's OK.

**Comment by filipeximenes** [comment]
@sv0 Awesome, thanks!

**Review by DanceParty — APPROVED** [review]

**Pull request closed without merging**
