### PR TITLE
Fixing the issue with static files loading from media

### PR DESCRIPTION
**Pull request by wldcordeiro**
#39 wasn't entirely fixed. This corrects those issues entirely.

### CODE REVIEW

**Comment by nielsonsantana** [comment]
Thanks @wldcordeiro. I'm having issues with the version 1.8.1.
Then, I think that it was solved.

**Comment by wldcordeiro** [comment]
@klen Could we get this and #42 merged into the project? They should fix several issues.

**Comment by klen** [comment]
Sorry, I was a little bit busy. Thank you for the request.

**Comment by wldcordeiro** [comment]
@klen Awesome thanks! :grin:  Great Django package man. I think I might be making another PR soon to bump that coverage percentage up to 100%.

**Pull request merged**
